### ISSUE TITLE
将参数save_weights_only=True修改为=False，来使用model.save()函数保存权重和结构出错

### ISSUE THREAD

**Issue by luoqianer** [bubbliiiing/pspnet-keras#1]
# 环境
系统：windows10
IDE：VSCode

# 问题：
将
```
checkpoint_period = ModelCheckpoint(log_dir + 'ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5',
                                    monitor='val_loss', save_weights_only=True, save_best_only=False, period=1)
```
中的参数save_weights_only=True修改为=False，目的是使用model.save()函数保存权重和结构到模型文件，
```
checkpoint_period = ModelCheckpoint(log_dir + 'ep{epoch:03d}-loss{loss:.3f}-val_loss{val_loss:.3f}.h5',
                                    monitor='val_loss', save_weights_only=False, save_best_only=False, period=1)
```
# 报错：
```python
11/11 [==============================] - 63s 6s/step - loss: 0.7309 - _f_score: 0.4748 - val_loss: 2.1645 - val__f_score: 0.1034
Traceback (most recent call last):
  File "e:/Software/AI/DeepLearn/Frame/Keras/pspnet-keras/pspnet-keras/pspnet-keras/train.py", line 125, in <module>
    callbacks=[checkpoint_period, reduce_lr,tensorboard])
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py", line 2262, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\callbacks.py", line 458, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\topology.py", line 2580, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\models.py", line 111, in save_model
    'config': model.get_config()
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\topology.py", line 2421, in get_config
    return copy.deepcopy(config)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\DigCore\Anaconda3\envs\tensorflow-gpu\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
```

**Comment by bubbliiiing** [comment]
重下代码，已解决
